### ISSUE TITLE
Project with spider for UE4.18?

### ISSUE THREAD

**Issue by juaxix** [rnixik/spider-navigation-plugin#2]
Can you add the project of your demo for Unreal Engine 4.18 here in github?

**Comment by juaxix** [comment]
I can't use that project with 4.18, you have to fix the .cs ,this is the error
`Running E:/UDK/UE_4.18/Engine/Binaries/DotNET/UnrealBuildTool.exe  -projectfiles -project="E:/dev/UnrealProjects/spiderNavigation/ThirdPersonDemo.uproject" -game -rocket -progress
Discovering modules, targets and source code for project...
While compiling E:\dev\UnrealProjects\spiderNavigation\Intermediate\Build\BuildRules\ThirdPersonDemoModuleRules.dll:
ERROR: e:\dev\UnrealProjects\spiderNavigation\Source\ThirdPersonDemo.Target.cs(19,12) : error CS0122: 'UnrealBuildTool.UEBuildBinaryConfiguration' no es accesible debido a su nivel de protecci?n
ERROR: e:\dev\UnrealProjects\spiderNavigation\Source\ThirdPersonDemo.Target.cs(17,23) : error CS0051: Incoherencia de accesibilidad: el tipo de par?metro 'ref System.Collections.Generic.List<UnrealBuildTool.UEBuildBinaryConfiguration>' es menos accesible que el m?todo 'ThirdPersonDemoTarget.SetupBinaries(UnrealBuildTool.TargetInfo, ref System.Collections.Generic.List<UnrealBuildTool.UEBuildBinaryConfiguration>, ref System.Collections.Generic.List<string>)'
ERROR: e:\dev\UnrealProjects\spiderNavigation\Source\ThirdPersonDemoEditor.Target.cs(19,12) : error CS0122: 'UnrealBuildTool.UEBuildBinaryConfiguration' no es accesible debido a su nivel de protecci?n
ERROR: e:\dev\UnrealProjects\spiderNavigation\Source\ThirdPersonDemoEditor.Target.cs(17,23) : error CS0051: Incoherencia de accesibilidad: el tipo de par?metro 'ref System.Collections.Generic.List<UnrealBuildTool.UEBuildBinaryConfiguration>' es menos accesible que el m?todo 'ThirdPersonDemoEditorTarget.SetupBinaries(UnrealBuildTool.TargetInfo, ref System.Collections.Generic.List<UnrealBuildTool.UEBuildBinaryConfiguration>, ref System.Collections.Generic.List<string>)'
ERROR: UnrealBuildTool Exception: Unable to compile source files.`

**Comment by rnixik** [comment]
You can do changes by yourself to fix this error.
From
`public Blabla(TargetInfo Target)`

Into 
`public Blabla(ReadOnlyTargetRules Target) : base(Target)`

in *.Build.cs

**Comment by juaxix** [comment]
Ok, I have found the fix in [this post](https://answers.unrealengine.com/questions/718575/error-when-updating-to-418-generating-visual-studi.html). Where you use "ThirdPersonDemo" instead of "RC" int the screenshots.
